version: '3'

services:
  postgres:
    container_name: gympoint-postgres
    image: postgres:11
    ports:
      - '5432:5432'
    volumes:
      - postgres:/var/lib/postgresql/data
    env_file: ./.env
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_PASSWORD=${DB_PASS}

  mongo:
    container_name: gympoint-mongo
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - mongo:/data/db

  redis:
    container_name: gympoint-redis
    image: redis:alpine
    ports:
      - '6379:6379'
    volumes:
      - redis:/data

volumes:
  postgres:
  mongo:
  redis:
